name: Java CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: ['8', '11', '15']
    steps:
      - uses: actions/checkout@v1
      - name: Setup java
        uses: joschi/setup-jdk@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: x64
      - run: mvn -v
      - run: mvn --batch-mode --no-transfer-progress --settings=settings.xml package
      - run: mvn --batch-mode --no-transfer-progress --settings=settings.xml exec:java -Dexec.mainClass="com.github.fwilhe.Dummy"
